---
- name: Set ENV & Git vars
  set_fact:
    git_username: "{{ lookup('pipe', 'git config user.name') }}"
    branch_name: "{{ lookup('pipe', 'git branch --show-current') }}"
    target_env_url: "https://{{ project.site_hosts | map(attribute='canonical') | first }}|{{ site }} {{ env }}"
    ci_job_url: "{{ lookup('env', 'CI_JOB_URL') }}"
  ignore_errors: yes

- name: Send initial deployment notification to Slack
  slack:
    token: "{{ slack_deploy_token }}"
    attachments:
      - text: "*{{ git_username }}* started deploying 🔀`{{ branch_name }}` to *<{{ target_env_url }}>* {% if ci_job_url | length > 0 %}[<{{ ci_job_url }}|🔎>]{% endif %}"
        color: warning
  with_items: "{{ vault_wordpress_sites[site].slack_deploy_token }}"
  loop_control:
    loop_var: slack_deploy_token
  when:
    - vault_wordpress_sites[site].slack_deploy_token is defined
    - vault_wordpress_sites[site].slack_deploy_token | length > 0
  delegate_to: localhost
  ignore_errors: yes
